### ISSUE TITLE
PAT Updating measures doesn't preserve argument order

### ISSUE THREAD

**Issue by kflemin** [NREL/OpenStudio-PAT#39]
_From @shorowit on September 1, 2017 17:38_

If I update a measure in PAT where I've inserted an argument at the top of the measure.rb, the argument appears at the end of the measure in PAT. If I want the argument to correctly appear at the top, I have to delete the measure from my project, re-add it, and then re-enter all of the argument values.

It may not sound too bad, but I have to update four PAT projects, each with this measure duplicated multiple times, so it creates a fairly lengthy process for me.

_Copied from original issue: NREL/OpenStudio#2770_

**Comment by kflemin** [comment]
@shorowit, does the displayed order of the arguments in PAT make a difference in the results? Or is it just that you'd rather have them in order?

**Comment by shorowit** [comment]
No, it does not make a difference in the results. But the order can be important for the user to understand what the arguments mean.

**Comment by kflemin** [comment]
Fixed in 674a9f54552d0c072e78b93955b2bb239586e3c5

**Comment by DavidGoldwasser** [comment]
@kflemin I still see this behavior in my build using current develop of PAT

**Comment by kflemin** [comment]
@DavidGoldwasser can you send me a pat project and a bit more detail about the behavior you are seeing  (did you add a new argument?  switch the order of 2 existing arguments? etc...)
